# Generated by Django 5.0.14 on 2025-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petites_annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
