# Generated by Django 5.2.1 on 2025-05-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petites_annonces', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='petites_annonces.adcomment'),
        ),
    ]
